local servers = {
	"html",
	"cssls",
	"ts_ls",
	"clangd",
	"pyright",
	"rust_analyzer",
	"tailwindcss",
	"bashls",
	"gopls",
	"dockerls",
	"yamlls",
	"jsonls",
	"marksman",
	"lua_ls",
	"jdtls",
	"dartls",
	"zls",
	"sqls",
	"graphql",
}

vim.lsp.config("emmet_language_server", {
	cmd = { "emmet-language-server", "--stdio" },
	filetypes = {
		"css",
		"eruby",
		"html",
		"javascriptreact",
		"less",
		"sass",
		"scss",
		"pug",
		"typescriptreact",
	},
	root_markers = { ".git" },
	settings = {
		includeLanguages = {},
		excludeLanguages = {},
		extensionsPath = {},
		preferences = {},
		showAbbreviationSuggestions = true,
		showExpandedAbbreviation = "always",
		showSuggestionsAsSnippets = true,
		syntaxProfiles = {},
		variables = {},
		triggerCharacters = { ">", ".", "#", "*", "(", "[", "{" },
	},
})

vim.lsp.enable({ "emmet_language_server", unpack(servers) })
