# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(2A2A2D)
$foreground = rgb(F8ECE1)
$color0 = rgb(4F4F53)
$color1 = rgb(262730)
$color2 = rgb(544C4A)
$color3 = rgb(585C70)
$color4 = rgb(827164)
$color5 = rgb(66988C)
$color6 = rgb(B0967E)
$color7 = rgb(EDDBCB)
$color8 = rgb(A6998E)
$color9 = rgb(323440)
$color10 = rgb(706563)
$color11 = rgb(757B96)
$color12 = rgb(AD9786)
$color13 = rgb(88CABB)
$color14 = rgb(EBC9A8)
$color15 = rgb(EDDBCB)
