# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(210E00)
$foreground = rgb(C4FFFF)
$color0 = rgb(342418)
$color1 = rgb(696969)
$color2 = rgb(5F7F7F)
$color3 = rgb(5C876C)
$color4 = rgb(44B7B3)
$color5 = rgb(43BABA)
$color6 = rgb(40BFBF)
$color7 = rgb(A2F7F7)
$color8 = rgb(71ADAD)
$color9 = rgb(8C8C8C)
$color10 = rgb(7EA9A9)
$color11 = rgb(7BB58F)
$color12 = rgb(5BF4EF)
$color13 = rgb(59F8F8)
$color14 = rgb(56FFFF)
$color15 = rgb(A2F7F7)
