# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */  
# /* wallust template - colors-hyprland */ 

$background = rgb(1E2124)
$foreground = rgb(B7D3E0)
$color0 = rgb(44474B)
$color1 = rgb(091A27)
$color2 = rgb(091D2C)
$color3 = rgb(0A2131)
$color4 = rgb(1C4B64)
$color5 = rgb(7B3E12)
$color6 = rgb(26607D)
$color7 = rgb(90B7CB)
$color8 = rgb(65808E)
$color9 = rgb(0C2234)
$color10 = rgb(0C273A)
$color11 = rgb(0E2C41)
$color12 = rgb(266485)
$color13 = rgb(A45318)
$color14 = rgb(3280A7)
$color15 = rgb(90B7CB)
